### PR TITLE
upgrade go mod core contract version

### PR DESCRIPTION
**Pull request by tingyuz**
Signed-off-by: Tingyu Zeng <tingyu.zeng@rsa.com>

### CODE REVIEW

**Review by tsconn23 — APPROVED** [review]

**Comment by tsconn23** [comment]
Error from Jenkins indicates that while this is the correct change to update the go-mod-core-contracts reference, the code was never built locally. The import path for the logging and related references in the code needs to be fixed.
```
11:02:54 go: finding github.com/edgexfoundry/go-mod-core-contracts/clients/logging latest
11:02:54 go: finding github.com/edgexfoundry/go-mod-core-contracts/clients latest
11:02:54 main.go:32:2: unknown import path "github.com/edgexfoundry/go-mod-core-contracts/clients/logging": cannot find module providing package github.com/edgexfoundry/go-mod-core-contracts/clients/logging
11:02:54 make: *** [build_worker] Error 1
11:02:54 Build step 'Execute shell' marked build as failure
```

https://github.com/edgexfoundry/go-mod-core-contracts/blob/c482d7c75c33440653bf0ca5836cf39eac998138/clients/logger/logger.go#L19

**Review by tsconn23 — CHANGES_REQUESTED** [review]
Error from Jenkins indicates that while this is the correct change to update the go-mod-core-contracts reference, the code was never built locally. The import path for the logging and related references in the code needs to be fixed.
```
11:02:54 go: finding github.com/edgexfoundry/go-mod-core-contracts/clients/logging latest
11:02:54 go: finding github.com/edgexfoundry/go-mod-core-contracts/clients latest
11:02:54 main.go:32:2: unknown import path "github.com/edgexfoundry/go-mod-core-contracts/clients/logging": cannot find module providing package github.com/edgexfoundry/go-mod-core-contracts/clients/logging
11:02:54 make: *** [build_worker] Error 1
11:02:54 Build step 'Execute shell' marked build as failure
```

https://github.com/edgexfoundry/go-mod-core-contracts/blob/c482d7c75c33440653bf0ca5836cf39eac998138/clients/logger/logger.go#L19

**Comment by tingyuz** [comment]
ok I see the path is changed. just upgrade and had another push.

**Review by tsconn23 — APPROVED** [review]

**Review by tsconn23 — CHANGES_REQUESTED** [review]
This is very complicated. The service fails to run because the `lc`variable is not initialized. I was unable to run the service initially because in the makefile, the OS target is specified as linux

`GO=CGO_ENABLED=0 GO111MODULE=on GOOS=linux go`

Once I removed the `GOOS` flag, I was able to run the service and received the following error.

```
/Documents/code/git/tsconn23/security-secret-store/core $ ./edgex-vault-worker
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1474149]

goroutine 1 [running]:
main.main()
	/Users/tconn/Documents/code/git/tsconn23/security-secret-store/core/main.go:40 +0x39
```

As you can see, line 40 is the first usage of `lc` which is not initialized.

**Comment by tingyuz** [comment]
Had another change and ran a local test with success. Let me run more testing and will have another push soon.

**Comment by tingyuz** [comment]
The local testing is successful with the latest change. Here is the log with local-built docker image:

edgex-files is up-to-date
edgex-core-consul is up-to-date
edgex-vault is up-to-date
Creating edgex-vault-worker ... done
Attaching to edgex-vault-worker
edgex-vault-worker | level=INFO ts=2019-05-30T19:23:07.2666098Z app=securityservice source=main.go:47 msg="-------------------- Vault Worker Cycle ------------------------"
edgex-vault-worker | level=INFO ts=2019-05-30T19:23:07.2856594Z app=securityservice source=main.go:96 msg="Successful loading the rootCA certificate."
edgex-vault-worker | level=INFO ts=2019-05-30T19:23:07.352935Z app=securityservice source=vault-worker.go:78 msg="Vault Health Check HTTP Status: 501 Not Implemented (StatusCode: 501)"
edgex-vault-worker | level=INFO ts=2019-05-30T19:23:07.3710274Z app=securityservice source=main.go:128 msg="Vault is not initialized (Status Code: 501). Starting initialisation and unseal phases."
edgex-vault-worker | level=INFO ts=2019-05-30T19:23:07.3821384Z app=securityservice source=vault-worker.go:92 msg="Vault Init Strategy (SSS parameters): Shares=5 Threshold=3"

**Review by tsconn23 — APPROVED** [review]

**Pull request merged**
