### PR TITLE
skip the cert generation as it is done by vault container. Instead re…

### PR DESCRIPTION
**Pull request by tingyuz**
…ad cert key pair from file system and load to vault.

Signed-off-by: tingyu.zeng@rsa.com <tingyu.zeng@rsa.com>

### CODE REVIEW

**Comment by tingyuz** [comment]
The build failure is from the output of console here:

23:32:14 Step 7/12 : COPY pkisetup.src/pkisetup .
23:32:14 COPY failed: stat /var/lib/docker/tmp/docker-builder763657451/pkisetup.src/pkisetup: no such file or directory

pkisetup is created by make file, so wondering if the CI/CD server calls the make build to create the binary.

**Review by alain2sf — COMMENTED** [review]
@tingyu Some first comments... I'm still reading the modified files from the PR.

1. The WATCHDOG_DELAY=3m was removed from the Docker Compose file, then I don't see the loop into the new vault worker, and I can't see where you can modify this interval using variable. We should probably implement the same loop logic that Ian did implement in the branch where he has made modifications related to Snap integration. 

2. There is still a generateCerKeyPair() function in certgen.go, I thought you will be using the Kong generated cert/key (during Vault image build) for both Kong usages. Also as the vault worker should not generate any cert/key anymore, we should rename this Go file (certgen would be confusing).

Some other consideration:

Every time Vault service is manually stopped/started/restarted from Docker CLI (docker-compose stop/start) it needs to be unsealed (init is normally a one time operation, obviously if the Vault container is not removed and the volumes deleted). 

The way the original vault-worker script worked was, to perform an init anyways, then if HTTP 200 it was a first time init, if HTTP 400 it was an already initialized Vault and the next phase would be to unseal with existing rest-init.json materials.

I was testing a docker-compose stop and a docker-compose start use case to double check if vault-worker.sh was still handling the restart with new Vault service. And then I became confused, even if everything is working fine, after the docker-compose stop/start the rest-init.json and rasp-unseal.json were rewritten

root@edgex-vault:/vault/config/assets # ls -l
total 24
-rw-r--r--    1 vault    vault          222 Sep 13 21:38 resp-init.json
-rw-r--r--    1 vault    vault          217 Sep 13 21:47 resp-unseal.json

root@edgex-vault:/vault/config/assets # ls -l
total 24
-rw-r--r--    1 vault    vault          222 Sep 13 21:51 resp-init.json
-rw-r--r--    1 vault    vault          217 Sep 13 21:51 resp-unseal.json


So I drilled down why, and I saw that the 2 JSON files were also having a different content:


BEFORE STOP
{
  "keys": [
    "308c2cec75dabdd643fbe66d39d63ba91fd33824ab4901dbc16ae59bef7e2558"
  ],
  "keys_base64": [
    "MIws7HXavdZD++ZtOdY7qR/TOCSrSQHbwWrlm+9+JVg="
  ],
  "root_token": "838bd5ba-4821-7884-70c2-c69913f44d04"
}

AFTER STOP
{
  "keys": [
    "3f037c35805d7e012f5894ff38ba7b4e6564f2b62588a22a8d00bb34eb1a83bc"
  ],
  "keys_base64": [
    "PwN8NYBdfgEvWJT/OLp7TmVk8rYliKIqjQC7NOsag7w="
  ],
  "root_token": "120e8e16-d2e8-8588-9461-1e3591459a4a"
}

BEFORE STOP
{
  "type": "shamir",
  "sealed": false,
  "t": 1,
  "n": 1,
  "progress": 0,
  "nonce": "",
  "version": "0.10.2",
  "cluster_name": "vault-cluster-a7c88cd8",
  "cluster_id": "155551c5-4b85-a82c-7c07-0b7a1d940f7a"
}

AFTER STOP
{
  "type": "shamir",
  "sealed": false,
  "t": 1,
  "n": 1,
  "progress": 0,
  "nonce": "",
  "version": "0.10.2",
  "cluster_name": "vault-cluster-1809fa74",
  "cluster_id": "cb76adcc-8800-57f4-7b7f-dacc732ed8f5"
}

Now I'm a bit more confused... Performing an init on an already initialized Vault seems to "work" as the new unseal key(s) are renewed as well as the Root Token. I know that in the Golang code, we perform an init check with Vault API before, so the new vault-worker works a bit differently and the resp-*.json should not be rewritten and changed. Can you double check this use case? Thanks.

**Comment by tingyuz** [comment]
@alain2sf  I have updated the code base to address item 2 as well as the resp-init.json issue. 

Regarding the item 1 of WATCHDOG_DELAY, I would prefer to leave it to the snap specific but not in the general go implementation as I haven't observed any significant delay after vault initialization. Let me know what you think.

**Comment by tingyuz** [comment]
ok, I have added the loop with "wait" parameter back. I decided to put the watch dog variable as one of the input parameters for vault-worker but not in the environment variable since it may be better to have these parameters into the same place, not spreading into different files.

**Comment by alain2sf** [comment]
@tingyuz Could you add the "command" tag in the Docker Compose Yaml file for the vault-worker service, so that the parameters (defaults) could already be there and would be easily handled. Like command: ["bundle", "exec", "thin", "-p", "3000"]. Thanks! 

By default the Vault TLS certificate is not verified (skip), did you test when the -init is set to not skip the verification? Where/how are you getting the CA certificate then?

**Comment by tingyuz** [comment]
@alain2sf added command tag into the vault-worker section of docker-compose-california-0.6.0-yml so that the time interval can be changed from docker compose file as well. 
For skip verification parameter, I haven't found a CA cert yet so all the testing are done with self-signed cert. I am thinking to get cert from letsencrypt.org, can you check if we can test this scenario?

**Comment by alain2sf** [comment]
@tingyuz The CA signing cert is under the same directory as the Vault and Kong cert. If you use it to verity the Vault cert (signed by this self signed CA) you are good to go. I was also thinking about using Let's Encrypt, although the max TTL for their cert is 90 days, which will become inconvenient even if we implement auto renewal. The main difference between LE and a classic CA is the ACME protocol instead of a proprietary mechanism (that could be manual). So, there is no one size fit all method I guess. Let's keep the LE or real CA use case for later on, for Edinburgh, so we can investigate and try without rushing things.

**Comment by alain2sf** [comment]
@tingyuz  The initial shell scripts were using the signing CA pem to verify the Vault TLS cert. You can double check how I was implementing the mechanism for info.

**Comment by tingyuz** [comment]
@alain2sf  the testing with CA cert is done and code has been updated too.

**Review by alain2sf — APPROVED** [review]
LGFM Will do a full test/QA run today, get you posted soon.

**Pull request merged**
