### PR TITLE
Fixes for california 0.6.1

### PR DESCRIPTION
**Pull request by anonymouse64**
This PR implements the minimal amount of changes we need to run the security services in the snap for 0.6.1 California release. They are:

* Make `pki-setup.sh` and `vault-setup.sh` executable
* Use `_VAULT_SCRIPT_DIR` for referring to location of scripts
* Allow overriding of the hostnames for vault and kong when unsealing kong and setting up kong, as they will both be localhost in the snap.
* Don't chown in the snap, as the user `vault` won't exist.
* **Exit the loop when unsealing is successful in `vault-init-unseal`**

Note that the last change is bolded because while this seems like a bug for the snap, I'm not sure if it's supposed to be a feature for docker. @alain2sf @tingyuz is the `vault-worker` container supposed to stay alive indefinitely continuously trying to unseal the vault? It would seem to me that it shouldn't because:

1. If vault and/or the rest of edgex dies and comes back up again (in a sealed state), this container will automatically unseal it, which is undesirable because the rest of edgex isn't necessarily up and running at this point. I.e. we only want this container to run and unseal vault when it's run with the rest of edgex. 
2. It seems just wasteful of resources to continually check and attempt to unseal the vault for the time that the containers are all up and running.

It's possible I missed some mechanism in the docker scripts that kills/stops this script after the initial setup but even if it's the case that something in the docker packaging stops the container, we need a way to cleanly exit this script in the snap, which this PR does.

Corresponding PR for edgex-go: https://github.com/edgexfoundry/edgex-go/pull/464

### CODE REVIEW

**Comment by alain2sf** [comment]
The vault-worker container has to stay alive in order to unseal Vault in the eventuality where Vault container is stopped/started or restarted, Kong and the other EdgeX services will not be able to fetch their secret materials (PKI) in Vault, they will also have all their requests failing, and they don't have a way (nor the authorization) to request an unseal process. So Kong for example would be out of order and then outbound connections impossible.
Having Vault up and running before every other services (besides Consul) is then necessary and harmless to any other services that will start afterwards, on the contrary. Therefore vault-worker needs to act as a watchdog to always enable Vault before any other service would need it. vault-worker has a minimal footprint and does not use many CPU resources as waiting most of the time (cycle defined by a parameter that could be increased significantly).

**Comment by anonymouse64** [comment]
@alain2sf doesn't that kind of defeat the purpose of using a sealable vault to begin with? If an attacker is able to stop the vault container (or rather in the snap just the vault process), then shouldn't EdgeX just not work in this case because it was probably compromised? I'd think that if vault dies then something bad is happening and we should leave the vault sealed until manual intervention happens and we restart EdgeX fully. Perhaps I'm missing something here...

Regardless, it is doable to make the vault-worker run in the background, but I would like to still change the logic a little bit for startup time because what I see running the snap is roughly:

```
vault server is run
vault-worker starts running -> 
vault-worker attempts to unseal, but fails because vault isn't done yet
vault worker goes to sleep for WATCHDOG seconds
less than approximately 5 seconds later, vault is fully up and ready
vault-worker waits the remainder of WATCHDOG seconds
vault-worker unseals the vault
```

Which if we set WATCHDOG to `3m`, then the entire process ends up taking about 3m longer than it should. So if instead we could have 2 loops that work like (in psuedo-code):

```
numtries=0
loop1:
    vault-worker attempts to unseal
    if successful:
        vault-kong is started
        run loop2 in background
    else:
        numtries++
        sleep 1 second
        continue
    if numtries > MAX_TRIES
        exit 1
```
```
loop2:
    vault-worker attempts to unseal
    if successful:
        vault-kong is started
    else:
        sleep WATCHDOG seconds
    continue
```
This way we can make sure that vault-worker exits after some point if vault is never coming up and we don't hang indefinitely waiting for it. Additionally, it attempts to run quickly the first time and waits a long time in the future. The reason I really want to make the initial setup go by faster is that already on my pretty reasonably powerful laptop the amd64 snap takes over 2 minutes (without the security services) to fully startup, and the security services add about 3 more minutes. I haven't gotten a chance to test the security services on my ARM64 device, but running the normal snap takes like 5 minutes to start everything up without security services...

**Comment by anonymouse64** [comment]
@alain2sf another thing related to hostnames is that the `dig` command in the `vault-init-unseal` command doesn't work within the snap because the hostname for consul is incorrect. It's running:

```
dig +short +tcp -p8600 @edgex-core-consul vault.service.consul
dig +short +tcp -p8600 @edgex-core-consul  active.vault.service.consul
```
As I understand it, these commands are running DNS requests to consul the service `vault.service.consul` and `active.vault.service.consul`, but fail because consul isn't located at `edgex-core-consul` and are instead at `localhost` in the snap. Is that a correct understanding of these commands?
Also, if that is what it's doing, could we change these to something like:

```
dig +short +tcp -p8600 @${_CONSUL_SVC} vault.service.consul
dig +short +tcp -p8600 @${_CONSUL_SVC} active.vault.service.consul
```
then do something like:
```
_CONSUL_SVC=${_CONSUL_SVC:-edgex-core-consul}
```
in the vault-init-unseal script and in the snap we just override `_CONSUL_SVC=localhost`.

**Review by tonyespy — CHANGES_REQUESTED** [review]
Overall the changes look good, although I'd recommend adding the suffix HOST or HOSTNAME to the _*_SVC variables to make their usage clearer.

**Comment by tonyespy** [comment]
Regarding the vault-worker loop, I agree with @anonymouse64. I have in intense dislike for infinite loops in scripts, and Ian's points are well made, especially with respect to the 3m timeout value.  If we keep this mechanism, then implementing a two-stage retry look as Ian suggested makes a lot of sense performance wise.

IMHOP ideally service dependencies like this should be handled by the deployment mechanism not implemented by services themselves. @anonymouse64 how would we handle the case in a snap where vault crashes? If vault-worker was a one-shot service, is there a way to re-trigger it if/when vault restarts?  It may turn out that the current approach is the only feasible way to do this, however it definitely merits discussion.

I suggest extracting this change into its own PR and adding it to next week's Security WG agenda.  We may decide its not worthwhile to address in California, and instead just focus on fixing this correctly in Dehli.

One other thing I was surprised to see was the use of dig/DNS for Consul service lookups instead of using Consul's REST API like other services.

**Comment by alain2sf** [comment]
@anonymouse64 Regarding the dig command exercise, I totally agree, I thought about using a variable after the final push, then we decided to take care of this one for Delhi (during Golang migration) as we did not have time, and the scripts were meant to work within a complete EdgeX flow (Docker compose file dependent). I used dig from a Bash script it was way easier and faster (time constraints) for the purpose. For Delhi the goal is definitively to dump dig and use Golang Consul API or a classic Golang DNS library request.

Regarding the vault-worker loop, I initially set the watchdog interval to 3min during the QA as it was not really affecting the process, then we probably forgot to reduce this interval for the final release of the compose file (the variable is set that way). It makes sense, the delays would be awful. 

Your pseudo-code for the new loop is pretty much what the Golang migration would have implemented ;) I was never too happy about it originally (@tonyespy I'm not a big fan of infinite loops as well, specially in a Docker chain of service) but time was of the essence and I did not have much of it then... we were rushing things knowing it would be temporary (changed in Golang) and easily customizable with the WATCHDOG variable in the Docker compose file.

@tonyespy I also would believe such logic should be handled by the deployment mechanism and not atomically implemented by services themselves. This would be a better design pattern for the platform anyways, and limit such sidecar services. Tingyu and me had very little knowledge about the deployment mechanism (we are probably still rookies), and no time to integrate, and again this work was meant to be ephemeral because of the Delhi release and the Golang migration, we did not want to waste precious time with something that we would have probably dumped, or rewritten.

Obviously we should discuss further all together during the next Security WG calls about how to handle these use cases to apply them in the Golang migration process , because having vault-worker written as a one-shot service will induce some issues to be able to re-trigger it if/when Vault restarts, simply by admin action for example. We also could move some Vault configuration steps within the config-seed service, that would reduce logic and also exposed Docker volumes.

Happy to tackle these topics.

**Comment by alain2sf** [comment]
@tonyespy @anonymouse64  An idea perhaps would be to integrate a Docker HEALTHY step in the Vault image build and work the new logic from there... tbc

**Comment by tonyespy** [comment]
@alain2sf Thanks for all the comments and context, lots of good topics for Dehli.

In the short term, we'd like to see this PR land, as it's currently blocking Ian's edgex-go [california security PR](https://github.com/edgexfoundry/edgex-go/pull/464) (which I'm in the middle of re-reviewing).  Can you please approve, or if you still think there are changes required, let us know?

**Comment by alain2sf** [comment]
Overall the changes look fine, although I could not practically QA. I'd recommend leaving the vault-worker pattern as it is for now, but if you believe otherwise I'm obviously flexible.

**Comment by anonymouse64** [comment]
Okay, I'll change the logic as described above so that it continuously runs in the background, but also has two loops so that we can get quicker startup time when running from the snap. Thanks

**Comment by anonymouse64** [comment]
@alain2sf I force-pushed this branch without the vault-worker changes to it, I am now handling the advanced loop logic I mentioned above in edgex-go's snap script here : https://github.com/edgexfoundry/edgex-go/pull/464/files#diff-015a8c01425c6a771eb0836a46a81ec0R57

**Review by tonyespy — APPROVED** [review]
LGTM

**Comment by alain2sf** [comment]
Thanks Ian (@anonymouse64). LGTM as well.

**Comment by anonymouse64** [comment]
Thanks @alain2sf , can you approve and merge this?

**Review by alain2sf — APPROVED** [review]
LGTM

**Pull request merged**
