### PR TITLE
Feature/update version number

### PR DESCRIPTION
**Pull request by tingyuz**

### CODE REVIEW

**Comment by JPWKU** [comment]
@tingyuz Will need to rebase against california again.  The version bump LGTM but I'm gonna let someone from the security group approve the PR since it includes actual code changes.

**Comment by tingyuz** [comment]
@JPWKU all the code changes are carried over from Jim's last approval.. these are golang implementation of the same feature. They are in parallel with the original implementation.

**Comment by tingyuz** [comment]
@jpwhitemn  can you help Jeremy about reviewing my latest PR here? Thanks!

**Review by jpwhitemn — APPROVED** [review]

**Comment by anonymouse64** [comment]
This PR appears to have merged commits from master into california, which while I don't think will affect the snap at all, may break docker builds for 0.6.1 as there were a number of changes to the docker-compose that up to this PR were not on california.

PS: there is a difference between rebasing a branch and merging the branch here. I think as intended, the only changes intended for california were commits:

- e2e0dcc89efc5907cd7352101c118edf12c24ac4

and not:

- f62739219f4d6f16e4b749d075c0fea2efb4509b
- d55ae40b17c4a302278949abb4fd802a75b46120

which implement the go version of this repo.

I believe that @JPWKU meant for you to rebase commit e2e0dcc89efc5907cd7352101c118edf12c24ac4 onto california so that was the only change included in california. Because the conflicts were resolved by merging california into this branch, effectively california was merged into master, and then when this PR was merged, all of master was merged into california.

**Comment by anonymouse64** [comment]
@jpwhitemn @tingyuz was the go version of this project meant to go into california or 0.6.1?

**Comment by JPWKU** [comment]
If this PR was rebased off of master at any time then we need to revert it.

**Comment by JPWKU** [comment]
I'm actually going to guide a community member through the revert.  Volunteers?

**Comment by anonymouse64** [comment]
@JPWKU I can do it, but I already know how to do this kind of thing, so if your thinking was to help someone through who hasn't done it, I'll let someone else learn how to do this

**Pull request merged**
